#' Title
#'
#' @param X an object of class mcmc created by [fitEllipse()]
#' @param siber_obj an object generated by [createSiberObject2()]
#'
#' @return
#' @export
#'
#' @examples
extractCOV <- function(X, siberObject){
  
  # calculate the indices to look up for each group
  ff <- matrix(1:(siberObject$n.iso^2*n_groups), 
               nrow = siberObject$n.groups, byrow = TRUE)
  
  # convert to list by row for passing to map()
  location <- lapply(seq_len(nrow(ff)), function(i) ff[i,])
  
  # create some labels so we can keep track of which group is which
  names(location) <- paste0(1:siberObject$n.groups)
  
  # map over the column index locations of each of the groups' Sigma2 
  # data, extract it, convert it to a nxn matrix, store it as a list within a 
  # tibble and name the column using master_code as character of numeric 
  # for z-transformed Covariance matrix for 
  # group with the master_code == 1.
  out <- location %>% 
    imap(~ X %>% 
           as.matrix() %>% 
           as_tibble(., rownames = "index") %>%
           group_by(`index`) %>% 
           select("index", all_of(.x + 1)) %>% 
           # nest(.key = .y) %>%
           nest() %>% 
           ungroup() %>%
           mutate({{.y}} := map(`data`, 
                                \(x) matrix(as.matrix(x), 
                                            ncol = siberObject$n.iso, 
                                            nrow = siberObject$n.iso) )) %>% 
           select(all_of(.y)) %>%
           tibble()
         
    ) %>%
    bind_cols()
  
  
  out <- map2(out, siberObject$summary$cov, 
              \(x,y) x %>% map(\(z) backTransCOV(z,y))
  ) %>% as_tibble()
  
  return(out)
  
}