#' Calculate the Bayesian Standard Ellipse Area for all groups
#'
#' This function loops over each group within each community and calculates the
#' posterior distribution describing the corresponding Standard Ellipse Area.
#'
#' @param siberCOV the Bayesian ellipses as returned by [siberMVN()].
#' @param siberObject an object generated by [createSiberObject2()]
#' @return A tibble comprising two columns, the first indicates group encoded by
#'   master_code and the second column is the estimated Standard Ellipse Area on
#'   the scale of the original data.
#'
#' @export

siberEllipses2 <- function (siberFit, siberObject) {
  
  postCOV <- extractCOV(siberFit, siberObject)
  
  # backPostCOV <- backTransCOV(postCOV, siberObject)
  
  SEAB <- map(postCOV, \(x) x %>% map_vec(\(z) siberNSEA(z)) %>% data.frame()) %>%
    bind_rows(.id = "master_code") %>% 
    mutate(master_code = as.numeric(master_code)) %>%
    rename("SEA_B_post" = ".")
  
 return(SEAB)
}
